trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - v*

pr:
  - master

pool:
  vmImage: ubuntu-20.04

variables:
  - group: NuGet
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: configuration
    value: Release
  - name: project
    value: SourceEngine.Bsp

jobs:
  - job: build
    displayName: 'Build & Deploy'
    steps:
      - template: ci/build.yml
      - template: ci/deploy.yml
